### PR TITLE
PIRK-10: Upgrade and Enforce Java 8

### PR DESCRIPTION
**Pull request by smarthi**

### CODE REVIEW

**Comment by tellison** [comment]
Hey Suneel, this PR seems to have way more than the Java 8 upgrade.  Was that your intention?

There are a number of formatting changes that are contrary to the established project style, and import  statement rearrangements (maybe Eclispe vs. IntelliJ ordering war?), etc.

**Comment by smarthi** [comment]
@tellison yeah i slipped in a few other code cleanups as part of this. The formatting changes r the default from other apache projects, oops sorry about that didn't notice the formatting changes.

**Comment by smarthi** [comment]
@tellison please review. Also we need to remove the Java 7 jobs on travis after merging this PR.

**Comment by tellison** [comment]
+1 (non-binding)

There were other, non-formatting, changes in your original change.  I hope you'll submit them as a PR too.

**Comment by smarthi** [comment]
yeah, those other changes would be part of a bigger PR later. Thanks for ur
feedback.

**Comment by smarthi** [comment]
This PR is good to go, The travis build now runs with maven 3.3.9 and Java 8. Disabled rat check temporarily to get past travis build failures.

**Comment by ellisonanne** [comment]
+1 
Thanks adding back in the rat check.

**Comment by smarthi** [comment]
This is good to merge now. It enforces Java 8 and Maven 3.3.9 as also RAT checks for license headers.

**Pull request closed without merging**
