### PR TITLE
[PIRK-28]: Logger Statements Not Working in/from Drivers

### PR DESCRIPTION
**Pull request by smarthi**
I do see that the log4j2.properties is being packaged into target/classes folder, and the main method should automatically pick it up from there. 

There was an unnecessary dependency on log4j 1.2 in POM which has now been removed and could have been shadowing the log4j2 jar.

Could someone please test this patch and confirm if its working? I'll check on this later tonight.

### CODE REVIEW

**Comment by ellisonanne** [comment]
I'll take a look

**Comment by ellisonanne** [comment]
Does not appear to be working

**Comment by smarthi** [comment]
How do I test this out locally? Is there an example that I could go by?

**Comment by ellisonanne** [comment]
If you run the QuerierDriver (or ResponderDriver) locally you can test it out. For example, if you run

`java -cp target/pirk-0.0.1-SNAPSHOT-exe.jar org.apache.pirk.querier.wideskies.QuerierDriver`

it will use the properties loaded from the querier.properties file packaged with the jar and should bark the error messages from QuerierProps. Currently, it does not; you will just get the help message that prints out via QuerierDriverCLI line 71. If you change all logger.info/logger.error messages in QuerierProps to System.out.println you will see the output that you are supposed to see via the logging mechanisms.

**Comment by smarthi** [comment]
Please see the jira entry for the status on this. Also in one of the previous PRs, changed the jar package naming to be prefixed with apache- . The jar would now be apache-pirk-0.0.1-SNAPSHOT-exe.jar

**Comment by smarthi** [comment]
This PR is good and working now, Phew!! 
Please review and merge after Travis Build passes.

**Comment by ellisonanne** [comment]
+1 Thanks for tracking this down!

**Pull request closed without merging**
