### PR TITLE
[PIRK-33] : Create release profiles to facilitate Pirk releases

### PR DESCRIPTION
**Pull request by smarthi**
Tested a release:perform goal with profile = "signed_release".

### CODE REVIEW

**Comment by ellisonanne** [comment]
+1 

There is one typo in the scm section that we need to change to remove 'nifi' and change to the correct pirk repo:

`<scm>
		<connection>scm:git:git://git.apache.org/nifi.git</connection>
		<developerConnection>scm:git:https://git-wip-us.apache.org/repos/asf/incubator-pirk.git</developerConnection>
		<url>https://git-wip-us.apache.org/repos/asf?p=incubator-pirk.git</url>
		<tag>HEAD</tag>
	</scm>`

I can change it as I merge (pls let me know if this is not the correct protocol - just trying to make it easy)...

**Comment by smarthi** [comment]
I can fix that, will update the PR in a few mins.

**Comment by smarthi** [comment]
Updated the PR, thanks for the feedback

**Comment by ellisonanne** [comment]
OK - will merge

**Pull request closed without merging**
