### PR TITLE
[PIRK-44]: Tachyon FS Error

### PR DESCRIPTION
**Pull request by ellisonanne**
Added a filter for org.tachyonproject to the shade plugin configuration to fix the issue.

### CODE REVIEW

**Comment by smarthi** [comment]
running an mvn dependency:tree on the project shows that the tachyon plugins are being pulled in with hadoop-mapreduce-client-core jar. 

You can exclude tachyon while pulling in the jar as a dependency (similar to how we r excluding storm dependencies being pulled in now by Elasticsearch).

**Comment by smarthi** [comment]
Looking at the maven dependency tree, Tachyon client is being pulled in as a dependency via hadoop-mapreduce-core-client, spark-core, elasticsearch-spark-core.

We could either individually exclude tachyon-client in the each of the above 3 dependencies OR go with the suggested solution in this PR.

**Comment by ellisonanne** [comment]
Oops - look like we crossed paths with you posting a comment to the PR while I was merging/closing the PR. I went with the current solution as Walter gave a +1 on the dev list earlier. We can reopen if folks would like...

**Comment by smarthi** [comment]
Did u try running on a Spark cluster with this fix? If it works fine on a spark cluster, then we can go ahead with this fix; else we should reopen.

**Comment by ellisonanne** [comment]
Yes, tested successfully on a Spark cluster

**Pull request closed without merging**
