### PR TITLE
[PIRK-50] -- Update POM for Release

### PR DESCRIPTION
**Pull request by ellisonanne**
Added the profile information for apache-release so that mvn release would function. 

It appears that we need to include an additional repo in the pom for releasing in order for 'mvn release:perform' to function correctly. NiFi seems to use https://repository.apache.org/content/repositories/releases. Should we do the same?

### CODE REVIEW

**Comment by smarthi** [comment]
We need to add the apache repositories to POM in <repositories> section. We can copy that from what's presently in NiFi/pom.xml

**Comment by ellisonanne** [comment]
Done

**Comment by smarthi** [comment]
You can remove the <apache-release> profile and update ur settings.xml. I
don't think this is needed in pom.

**Comment by smarthi** [comment]
We can close this PR without merging. The POM is good now.

**Pull request closed without merging**
