### PR TITLE
[PIRK-2] Load Pallier's PRNG statically and from any provider.

### PR DESCRIPTION
**Pull request by tellison**
Tested with Oracle jdk180_91 and IBM 8.0.3.0.

### CODE REVIEW

**Comment by eawiliams** [comment]
As different providers of NativePRNG may have different implementations, we want to give users the ability to specify their provider. Thus, we need to add config option(s) to specify the the provider or default to 'SUN' and fail over to grab the system-default NativePRNG.

**Comment by tellison** [comment]
The configuration of providers is made in the runtime (in the lib/security/java.security) rather than the application.  Why would Pirk need to specify a specific provider?

**Comment by eawiliams** [comment]
For the user that would like to remove the ambiguity of the provider, adding a configuration option to specify the provider seems reasonable. Additionally, as the SecureRandom constructor explicitly provides for this option:

SecureRandom(SecureRandomSpi secureRandomSpi, Provider provider)

it makes sense to extend it outwards to Pirk.

**Comment by eawiliams** [comment]
Going to accept this pull request now and then follow up with a JIRA issue to add the Provider (for SecureRandom) as a configuration option in Pirk.

**Pull request closed without merging**
