### PR TITLE
[PIRK-30]: Pirk compile no longer fails with RAT checks

### PR DESCRIPTION
**Pull request by smarthi**

### CODE REVIEW

**Comment by ellisonanne** [comment]
Travis is failing the PR with the following error:

[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.11:check (default) on project pirk: Too many files with unapproved license: 1 See RAT report in: /home/travis/build/apache/incubator-pirk/target/rat.txt -> [Help 1]

Does anyone know how to check/access the report /home/travis/build/apache/incubator-pirk/target/rat.txt? I've had this happen some and it just required a bit of cleaning...

**Comment by smarthi** [comment]
After long debugging and messing with Travis, here's the culprit

screen shot 2016-07-30 at 4 08 17 pm

**Comment by smarthi** [comment]
This issue is fixed now, and the PR is good to merge.

**Comment by ellisonanne** [comment]
+1 -- will merge now. Thanks for fixing this issue!

**Pull request closed without merging**
