### PR TITLE
[PIRK-17] - Add Ability to Embed QuerySchema in Query, plus minor misc cleanup

### PR DESCRIPTION
**Pull request by ellisonanne**

### CODE REVIEW

**Comment by ellisonanne** [comment]
It looks like there is some git weirdness here in that all diffs from the past few commits are showing up in the 'Files Changed' -- probably has something to do with the fact that I started working on an old copy of master and then updated... :(  I will see if I can make this any better.

**Comment by smarthi** [comment]
@ellisonanne Commit ur changes locally and then update from master, that way the last commit would be ur changes only.

**Comment by ellisonanne** [comment]
Yes - working on it now...

**Comment by ellisonanne** [comment]
Much better now - only 35 files changed :)

**Comment by smarthi** [comment]
lgtm +1. Ship it!

**Comment by smarthi** [comment]
Minor knitpick: Edit the title of this PR to read [PIRK-17] at the beginning - that way git can update the related jira.

**Comment by ellisonanne** [comment]
What does igtm stand for? A quick google search yielded: 

IGTM	Image Guided Treatment Management 
IGTM	International Golf Travel Market

Assuming that's not what you mean :)

**Comment by smarthi** [comment]
Its LGTM.

**Comment by smarthi** [comment]
it shuld be PIRK-17, notice the hyphen in between - that's how Jira has it.

**Comment by ellisonanne** [comment]
Ok - thanks

**Comment by tellison** [comment]
I don't see a committer's review completed on this PR  ;-)

**Comment by ellisonanne** [comment]
It was my understanding the members of the PMC (you, Suneel, etc) are also committers and able to perform a review in a RTC scenario. Suneel commented " LGTM +1. Ship it!" before it was committed and closed. I will post this same comment to the dev list and we can discuss there.

**Pull request closed without merging**
