### PR TITLE
[PIRK-16] Define XML schema definition files for Pirk's data and query schemas

### PR DESCRIPTION
**Pull request by tellison**
Reading the loader code, the "isArray" element is not optional.  Does it make sense and aid readability for me to tweak the loader to assume isArray is false by default? or do you want to keep it explicit?

### CODE REVIEW

**Comment by ellisonanne** [comment]
Designating the isArray default to 'false' makes sense. It seems that if we are going to have default values, we should be explicit and also specify 'required' on all attributes that are required. Thoughts?

**Comment by tellison** [comment]
Each element must occur once (i.e. minOccurs="1" maxOccurs="1") unless stated differently, so we just need to add a minOccurs="0" to isArray to make it optional, defaulting to true, so we can write <isArray/>.

I'll update this PR.

[It is also possible to define the set of allowed values for the <type> element, but since that may contain a class name as well as the primitive types, we can't usefully define it any better in the xsd.]

**Comment by tellison** [comment]
As well as supporting the original format, this PR allows for a more concise form, like this:

```
<schema>
    <schemaName>fakeDataSchema</schemaName>
    <element>
        <name>elementName1</name>
        <type>string</type>
    </element>
    <element>
        <name>elementName2</name>
        <type>int</type>
        <isArray/>
        <partitioner>org.apache.pirk.schema.data.partitioner.PrimitiveTypePartitioner</partitioner>
    </element>
    <element>
        <name>elementName3</name>
        <type>string</type>
        <isArray/>
        <partitioner>org.apache.pirk.schema.data.partitioner.IPDataPartitioner</partitioner>
    </element>
</schema>
```
Note: ```elementName1``` has no ```isArray``` element, so it is not an array; the other two don't need to specify a value for ```isArray```.

**Comment by ellisonanne** [comment]
+1 Looks good

**Pull request closed without merging**
