### PR TITLE
[PIRK-41]: Add JSON Serialization for Java Objects

### PR DESCRIPTION
**Pull request by smarthi**

### CODE REVIEW

**Comment by ellisonanne** [comment]
Hi Suneel - How did you test this? We should include quick/simple unit tests for all custom SerializationServices.

**Comment by smarthi** [comment]
I was debating if I shuld do that as part of this PR or not. I'll go ahead
and do it.

**Comment by ellisonanne** [comment]
Thanks! :)

**Comment by smarthi** [comment]
Added very basic simple tests for Java and Json Serializers.

**Comment by ellisonanne** [comment]
+1 looks good

**Pull request closed without merging**
